# -*- coding: utf-8 -*-
"""hate speech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-WAEao6HIUrCaHNAJ2EvANk8KC1qb51t
"""

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = [
    "I hate you",
    "You are an idiot",
    "I will kill you",
    "You are worthless",
    "I love this",
    "This is amazing",
    "I appreciate your help",
    "You are so kind",
    "You are horrible",
    "I really love this",
    "You are the worst",
    "You are amazing",
    "I despise your existence",
    "Such a nice person",
    "You are disgusting",
    "Fantastic job",
    "I want to hurt you",
    "This made my day",
    "Pathetic loser",
    "You are brilliant"
]

labels = [1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]

tokenizer = Tokenizer(num_words=1000, oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)
padded_sequences = pad_sequences(sequences, padding='post')

model = keras.Sequential([
    keras.layers.Embedding(1000, 16, input_length=padded_sequences.shape[1]),
    keras.layers.GlobalAveragePooling1D(),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(padded_sequences, np.array(labels), epochs=30)

test_sentences = [
    "You are horrible",
    "I really love this",
    "You are the worst",
    "You are amazing",
    "I despise your existence",
    "Fantastic job",
    "I want to hurt you",
    "You are brilliant"
]

test_sequences = tokenizer.texts_to_sequences(test_sentences)
test_padded = pad_sequences(test_sequences, maxlen=padded_sequences.shape[1], padding='post')

predictions = model.predict(test_padded)

for i, sentence in enumerate(test_sentences):
    pred_value = predictions[i][0]
    label = "Hate Speech" if pred_value >= 0.5 else "Not Hate Speech"
    print(f"{sentence} --> {label} (Confidence: {pred_value:.4f})")